name: Docker Image CI

on:
  push:
    branches: [ "yehiafarag-patch-1" ]
  pull_request:
    branches: [ "yehiafarag-patch-1" ]

jobs:
 test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.13.7" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m unittest discover -s segmentfunctionapp/test/test_app.py


